### ISSUE TITLE
remixaustin.com not reflecting latest changes

### ISSUE THREAD

**Issue by brookslybrand** [remix-austin/remixaustin-com#17]
I'm not super sure what's going on, but @sethdavis512's latest comment from #13 doesn't seem to show up on remixaustin.com.

If I pull the latest and run it locally, it's there, but not reflected on the prod site, even though [that commit did trigger a deploy](https://github.com/remix-austin/remixaustin-com/actions/runs/3449648839)

Not sure if this is a caching issue or what, but I imagine @grantnorwood would have the best idea

**Comment by grantnorwood** [comment]
Since his PR #16 wasn't merged to `main`, it didn't actually deploy to prod _(even though the GH Action is called "deploy")_.

I've merged that in now, and it's now reflected on prod!

I'll better organize/name the workflows for clarity.

**Comment by grantnorwood** [comment]
Still learning about reusable workflows, but it seems like separate workflows for "development" and "deploy" are working now.

I feel like the "Development" workflow may be running twice because it's shown on the GitHub Actions page twice ... I might need to remove the `pull_request` triggers from `development.yml` and only leave the `workflow_call` trigger 🤷‍♂️
